package network.ike.workspace;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import java.util.Map;

/**
 * Serializes a {@link VersionUpgradePlan} to YAML.
 *
 * <p>Unlike {@link ManifestWriter}, which edits in place to preserve
 * user comments, this writer produces the full file from scratch.
 * A versions-upgrade-plan is machine-generated and short-lived
 * (deleted after {@code versions-upgrade-publish}), so round-trip
 * comment preservation is not a goal.
 *
 * <p>Output format is stable: two-space indent, lowercase-hyphen
 * status values, quoted strings for versions (to avoid YAML
 * coercion of values like {@code "127"} to integers).
 */
public final class VersionUpgradePlanWriter {

    private VersionUpgradePlanWriter() {}

    /**
     * Write a plan to a YAML file. Overwrites without backup.
     *
     * @param plan the plan to serialize
     * @param path output path
     * @throws VersionUpgradePlanException if the file cannot be written
     */
    public static void write(VersionUpgradePlan plan, Path path) {
        try {
            Files.writeString(path, toYaml(plan), StandardCharsets.UTF_8);
        } catch (IOException e) {
            throw new VersionUpgradePlanException(
                    "Cannot write plan to " + path, e);
        }
    }

    /**
     * Render a plan as a YAML string.
     *
     * @param plan the plan to serialize
     * @return the YAML content, terminated with a newline
     */
    public static String toYaml(VersionUpgradePlan plan) {
        List<String> lines = new ArrayList<>();
        lines.add("# IKE Versions-Upgrade Plan");
        lines.add("# Generated by: mvn "
                + (plan.scope() == VersionUpgradeScope.WORKSPACE ? "ws" : "ike")
                + ":versions-upgrade-draft");
        lines.add("#");
        lines.add("# Edit this file to control what versions-upgrade-publish"
                + " applies:");
        lines.add("#   - delete an entire node section to skip that node");
        lines.add("#   - delete a property/literal entry to skip that upgrade");
        lines.add("#   - change the 'to:' value to pin a specific version");
        lines.add("#");
        lines.add("# Blocked entries are retained for transparency and will"
                + " not be applied.");
        lines.add("");

        lines.add("schema-version: \"" + plan.schemaVersion() + "\"");
        if (plan.generated() != null) {
            lines.add("generated: \"" + plan.generated() + "\"");
        }
        lines.add("scope: "
                + plan.scope().name().toLowerCase(Locale.ROOT));
        if (plan.planHash() != null) {
            lines.add("plan-hash: \"" + plan.planHash() + "\"");
        }
        if (plan.pomFingerprint() != null) {
            lines.add("pom-fingerprint: \"" + plan.pomFingerprint() + "\"");
        }
        if (plan.ikeToolingVersion() != null) {
            lines.add("ike-tooling-version: \""
                    + plan.ikeToolingVersion() + "\"");
        }

        lines.add("");
        lines.add("nodes:");
        if (plan.nodes().isEmpty()) {
            lines.add("  {}");
        } else {
            for (Map.Entry<String, NodeVersionUpgrade> entry
                    : plan.nodes().entrySet()) {
                appendNode(lines, entry.getKey(), entry.getValue());
            }
        }

        return String.join("\n", lines) + "\n";
    }

    private static void appendNode(List<String> lines, String name,
                                   NodeVersionUpgrade node) {
        lines.add("  " + name + ":");
        appendParent(lines, node.parent());
        appendProperties(lines, node.properties());
        appendLiterals(lines, node.literals());
    }

    private static void appendParent(List<String> lines,
                                     ParentVersionUpgrade parent) {
        if (parent == null) {
            lines.add("    parent: null");
            return;
        }
        lines.add("    parent:");
        lines.add("      groupId: \"" + parent.groupId() + "\"");
        lines.add("      artifactId: \"" + parent.artifactId() + "\"");
        lines.add("      from: \"" + parent.fromVersion() + "\"");
        lines.add("      to: \"" + parent.toVersion() + "\"");
        lines.add("      status: " + yamlStatus(parent.status()));
        if (parent.reason() != null) {
            lines.add("      reason: \"" + escape(parent.reason()) + "\"");
        }
    }

    private static void appendProperties(List<String> lines,
                                         List<PropertyVersionUpgrade> properties) {
        if (properties.isEmpty()) {
            lines.add("    properties: {}");
            return;
        }
        lines.add("    properties:");
        for (PropertyVersionUpgrade p : properties) {
            lines.add("      " + p.propertyName() + ":");
            lines.add("        from: \"" + p.fromVersion() + "\"");
            lines.add("        to: \"" + p.toVersion() + "\"");
            lines.add("        status: " + yamlStatus(p.status()));
            if (p.reason() != null) {
                lines.add("        reason: \"" + escape(p.reason()) + "\"");
            }
        }
    }

    private static void appendLiterals(List<String> lines,
                                       List<LiteralVersionUpgrade> literals) {
        if (literals.isEmpty()) {
            lines.add("    literals: []");
            return;
        }
        lines.add("    literals:");
        for (LiteralVersionUpgrade l : literals) {
            lines.add("      - groupId: \"" + l.groupId() + "\"");
            lines.add("        artifactId: \"" + l.artifactId() + "\"");
            if (l.location() != null && !l.location().isEmpty()) {
                lines.add("        location: \"" + l.location() + "\"");
            }
            lines.add("        from: \"" + l.fromVersion() + "\"");
            lines.add("        to: \"" + l.toVersion() + "\"");
            lines.add("        status: " + yamlStatus(l.status()));
            if (l.reason() != null) {
                lines.add("        reason: \"" + escape(l.reason()) + "\"");
            }
        }
    }

    private static String yamlStatus(VersionUpgradeStatus status) {
        return status.name().toLowerCase(Locale.ROOT).replace('_', '-');
    }

    private static String escape(String value) {
        return value.replace("\\", "\\\\").replace("\"", "\\\"");
    }
}
